### ISSUE TITLE
throttled-*-upper-threshold doesn't accept 0 or isn't documented well

### ISSUE THREAD

**Issue by WalkerCodeRanger** [sebdah/dynamic-dynamodb#222]
The "throttled-writes-upper-threshold" and "throttled-reads-upper-threshold" settings default to 0 according to the docs.  Zero is a reasonable value for this setting so we assumed this would mean that it should scale if there were any throttled reads or writes.  However, we found it wasn't.  Reading the code we find "if throttled_reads_upper_threshold > 0:" so it is clear that 0 is actually a special value meaning not set.

Ideally, 0 would be a legal value and not set would be -1 or max int value.  Changing that behavior and changing the default to match would only mess up the small number of people who explicitly set it to 0.

At a minimum, the docs should make it clear that 0 means don't check.

**Comment by Osterjour** [comment]
+1

**Comment by sebdah** [comment]
In order to keep backwards compatibility I'll only update the docs to reflect this.
