### ISSUE TITLE
Scaling up by percent doesn't seem to calculate the amount Correctly

### ISSUE THREAD

**Issue by jlpassm** [sebdah/dynamic-dynamodb#235]
I thought I understood the documentation, but Dynamic DynamoDB doesn't seem to work like I expected.

Dynamic DynamoDB recognizes that it should scale up and sends the notification. Then when it calculates the amount to scale up, it calculates what the current Read provisioning units are.

I expected once the event was recognized ( reads above 65%) that it would scale the reads up by 50%, which I expected to be 30*50% = 15 units, or scale up to 45 read units.  If I change percent to units and 50 to 15 in the configuration file it does scale up by 15 units.  I would prefer to use percent.

The read through put is currently set to 30 units and the log states that it will scale up to 30.0. This doesn't look correct to me. Here is the log:

![image](https://cloud.githubusercontent.com/assets/6538048/6235608/5d335f74-b6a9-11e4-9051-7b8dbeb22257.png)

The relevant section of my configuration file looks like this:

![image](https://cloud.githubusercontent.com/assets/6538048/6235626/85d55cca-b6a9-11e4-82c2-f7a3ff9db467.png)

**Comment by sebdah** [comment]
Thanks, this is a bug and it looks like it is caused by a faulty float conversion. I'm looking at it.

**Comment by sebdah** [comment]
I have pushed out a fix in 1.20.3, could you please test it on your environment?

**Comment by jlpassm** [comment]
I'll give it a shot.
What is the quickest easiest way to install the fix on my EC2 instance?

**Comment by sebdah** [comment]
pip install -U dynamic-dynamodb

**Comment by jlpassm** [comment]
Looks like it works like I expected now.  Nice work Sebastion.

Thanks!!!!!
