### ISSUE TITLE
Handle combinations of configuration file and command line options better

### ISSUE THREAD

**Issue by sebdah** [sebdah/dynamic-dynamodb#24]
Today Dynamic DynamoDB is more or less handling configuration files OR command line options. This should be changed so that combinations are supported. I think that command line options should have precedence over configuration file options.

**Comment by terryma** [comment]
I saw that this has been closed. I want to use the "lookback-window-start" option on the command line, and it doesn't appear to be available. When I define it in the config file, I can't seem to have the option picked up when I run dynamic-dynamodb with the -t option on the command line. Is this a supported usecase?

**Comment by sebdah** [comment]
Sorry for a late response to this. No, it is not a supported use case. I suggest that you write all your configuration in the configuration file if you need to have access to these more advanced configuration options.
