### ISSUE TITLE
Limits on scale down?

### ISSUE THREAD

**Issue by binoculars** [sebdah/dynamic-dynamodb#243]
In the [Limits in DynamoDB](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html) section of the Developer Guide, it says, "You can call `UpdateTable` to reduce provisioned throughput, but no more than four times in a single UTC calendar day."

Does this application include logic to limit decreases per UTC calendar day?

**Comment by sebdah** [comment]
Well, yes, but setting sensible config options to sensible values is crucial here. See slide 7 here for more details on config options: http://www.slideshare.net/SebastianDahlgren/auto-scale-dynamodb-with-dynamic-dynamodb-v10

**Comment by binoculars** [comment]
Thanks and I agree the utility is great, it just needs to be used judiciously. Nice presentation!
