### ISSUE TITLE
Minimum Scale Down By config option

### ISSUE THREAD

**Issue by joshowen** [sebdah/dynamic-dynamodb#245]
When scaling by percentages, it would be useful to be able to specify a minimum to scale by (never scale down 50% if its only 1 or 2 actual units).  This is useful for limiting the downscaling operations.

**Comment by Sazpaimon** [comment]
I would actually go one step further and say to have more granular downscaling so we can bring tables down to 1 read/write unit quickly if they suddenly stop getting used
