### ISSUE TITLE
Granularity for up-scaling, new up-scaling metrics and separation of throttled event/consumed units up-scaling

### ISSUE THREAD

**Issue by omnidavesz** [sebdah/dynamic-dynamodb#252]
Hi,

Following on from the email I sent a couple of weeks ago I forked dynamic-dynamodb to my repository and made the following changes:

•	Introduced 2 new metrics for measuring throttling. One being the number of throttled events as a percentage of provisioned units and other being the number of throttled events as a percentage of consumed units.

•	Restructured the logic for the ensure-provision-reads and ensure-provisioning-writes methods incore/table.py and core/gsi.py. Instead of one long if-else chain where scaling is only determined by one factor the new process will check how much up-scaling should occur as a result of consumption, number of throttled events (and, if configured, throttled events as a percentage of provisioned units and throttled events as a percentage of consumed units). Then the scaling amounts will be compared and the highest value will be taken as the scaling amount. The down-scaling logic has been separated from the up-scaling logic but it will be unaffected as a check has been introduced to prevent down-scaling if up-scaling is due to occur.

•	Introduced new config to enable separate amounts for up-scaling based on number of throttled events and consumption.

•	Introduced new config allowing users to pass in a dictionary containing key/value pairs enabling granular scaling for up-scaling by consumption, up-scaling by throttles with respect to provisioning and up-scaling by throttles with respect to consumption. The key/value pairs in the dictionary are for defining steps/bands for which the scaling policy can react slightly differently. This is somewhat akin to the **New Scaling Policies With Steps** for EC2 outlined [here] (https://aws.amazon.com/blogs/aws/auto-scaling-update-new-scaling-policies-for-more-responsive-scaling/). The key in this dictionary will be the scaling threshold and the associated value will be the scaling amount which will be used when this threshold is reached.

•	Up-scaling by number of throttled events is still present but due to the threshold being an absolute value rather than a percentage having granular scaling for this metric would be inappropriate.

•	Changed the return type of the **get_consumed_read_units_percent** and **get_consumed_write_units_percent** metrics from `int` to `float` in order to enable finer tuning of the scaling thresholds

•	Changed the input type of the **writes-upper-threshold** and **reads-upper-threshold** config options from `int` to `float` to match with the change in the metrics described above

•	All of the new config options are non-mandatory

•	Updated the configuration options docs page to describe the new config and created a new docs page to describe how the granular scaling will work

I'm currently testing these changes against my company's database to make sure that I haven't broken any existing functionality. If you're happy with what I've done could my branch be merged back into master?

**Comment by sebdah** [comment]
Thanks for all of this @omnidavesz. I'm back from vacation and family stuff and would happily read this through and iterate over it and eventually merge it. Feel free to open an pull request (or preferably more if possible for you) to my `develop` branch.

**Comment by sebdah** [comment]
This has been released in version 2.0.0

**Comment by Sazpaimon** [comment]
Can the documentation for this be looked at? I'm having a lot of trouble understanding it, especially with regards to the throttling settings.

**Comment by sebdah** [comment]
@Sazpaimon thanks for notifying me about this. It was simply a miss in the docs system. It's available now: https://dynamic-dynamodb.readthedocs.org/en/latest/granular_scaling.html

**Comment by Sazpaimon** [comment]
@sebdah I've already looked at that page in the docs, and it's still unclear to me why I would want a metric for throttles relative to consumed or provisioned throughput. In what scenario would either of those be useful versus just looking at consumed relative to provisioned?

**Comment by omnidavesz** [comment]
@Sazpaimon The previous version of the plugin already allowed users to enable up-scaling when throttle events occured. 

However the threshold that could be set was an absolute value of the number of throttle events that occurred in the check interval (currently 5 minute intervals are the minimum that CloudWatch provides). 

Therefore if one were to set 100 throttle events as the scaling threshold, up-scaling would occur if 100 or more throttle events occurred in the 5 minute period. However this ignores the potential that the throttles might have occurred in a short burst as a result of a partition getting suddenly hit hard. In that case many users (I'm assuming) wouldn't want to upscale their provisioning because of a small burst.

What the throttles by provision/consumed does is average out the number of throttles in this 5 minute period and calculates it as a percentage of the average provisioning/consumption in the same period. This also makes sense because the provisioning and consumption metrics are already provided as averages over the 5 minute period.

Additionally setting an absolute limit isn't suitable for default config for a lot of people as they could potentially have several tables all with different usage (e.g. 100 throttle events is different for a table consuming 200 IOPS than for a table consuming 2000 IOPS).

Sorry for jumping in but I though I might be able to clear these points up. If you have any further questions please feel free to ask.

**Comment by Sazpaimon** [comment]
Actually, as of yesterday, DynamoDB now reports these metrics at 1 minute intervals: https://aws.amazon.com/about-aws/whats-new/2015/08/dynamodb-update-enhanced-metrics-for-better-operational-insight/
