### ISSUE TITLE
Unable to install on Ubuntu using git

### ISSUE THREAD

**Issue by IgalSc** [sebdah/dynamic-dynamodb#253]
Hi
I'm on Ubuntu server 14.04
trying to copy the package using git I get error
ubuntu@MyServerName:~$ sudo git clone git@github.com:sebdah/dynamic-dynamodb.git
Cloning into 'dynamic-dynamodb'...
The authenticity of host 'github.com (IP_Address_Goes_Here)' can't be established.
RSA key fingerprint is Fingerprint_Goes_Here.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,IP_Address_Goes_Here' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by lcabral37** [comment]
You should check this page https://help.github.com/articles/which-remote-url-should-i-use/
And if you still think you need ssh protocol over https then check out how to set up your ssh key 
https://help.github.com/articles/generating-ssh-keys

**Comment by IgalSc** [comment]
@lcabral37 
I'm not sure I understand how the page you refer to helps here
The documentation for the project (http://dynamic-dynamodb.readthedocs.org/en/latest/installation.html) has this in Installation instructions:
"Manually via Git
It is also possible to install Dynamic DynamoDB manually, if you do no have access to pip. First checkout the project from GitHub:

git clone git@github.com:sebdah/dynamic-dynamodb.git"

This fails with the error message I posted.

**Comment by lcabral37** [comment]
The documentation is still technically correct. 
The error message is due to you not having setup your ssh keys for github so that the git client can use the ssh protocol.

But I would agree that in practice that the installation documentation page should refer to the https:// url for simplicity as the ssh URL only makes sense for maintainers of the project.

**Comment by IgalSc** [comment]
End user having to setup ssh keys for github should require some dev knowledge :)
Someone who needs the package only available here with no previous experience with github should be able to install following the documentation.
I can help with documentation if needed (not sure how to do it here), but I'm not a dev person and it's my second day on github

**Comment by IgalSc** [comment]
I would add here - when installing using pip, it is not clear where to create the dynamic-dynamodb.conf file or where the example file is located.

**Comment by sebdah** [comment]
I'm closing this at it is not really related to Dynamic DynamoDB.

> I would add here - when installing using pip, it is not clear where to create the dynamic-dynamodb.conf file or where the example file is located.

Thanks for the information. I do not intend to change that for now. The configuration file can exist anywhere if you simply use the `-c` flag when invoking the command.
