### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by IgalSc** [sebdah/dynamic-dynamodb#254]
Hi

The documentation on http://dynamic-dynamodb.readthedocs.org/ doesn't have the dynamic-dynamodb.conf and logging.conf location specified.

Using pip, the dynamic-dynamodb is installed under /usr/local/bin/ on Ubuntu.
It is not clear where the above mentioned configuration files should be located.

Thanks

**Comment by sebdah** [comment]
The configuration path can be specified by adding the `-c` flag when invoking `dynamic-dynamodb`. That flag is visible in the documentation and in `--help`. 

I'll consider merging a PR related to this, but I won't do any other change to this as I don't think this is a real issue for the user base.
