### ISSUE TITLE
Change Throughput Limit Exceeded

### ISSUE THREAD

**Issue by radleta** [sebdah/dynamic-dynamodb#256]
I started running the dynamic-dynamodb and ran into an issue where I configured the application to aggressively and it quickly ran out of the maximum of 4 updates per day within the first couple hours.

Here are some thoughts:

* Does anyone have any recommended suggestions for settings that would best compliment the limit of 4 changes per day?
* Do you think the documentation should be updated to warn users about the update limit?
* Do you think there should be a notification when updates can no longer be performed due to the throughput change limit of 4 being reached? (I think it should because it can be confusing as to why the dynamic-dynamodb isn't issuing changes.)

Thanks for the help.

Richard

**Comment by tcanabarro** [comment]
Hi Richard,

We use dynamic-dynamodb in Production to handle throughput to some 60~ tables. It took us a while to get the settings straight, but now we rarely see a `ProvisionedThroughputExceededException`. It boils down to you knowing your application and it's variations.

Here's the throughput char for the last week of one of our tables:
<img width="882" alt="screen shot 2015-08-03 at 10 34 53" src="https://cloud.githubusercontent.com/assets/3525362/9038541/650f1e36-39cb-11e5-92d0-fc4a5c6c8f9f.png">

You can see we overprovision to avoid exceptions in sudden spikes, and the downscale only happens after the levels have stabilised for a while. The setting `num-*-checks-before-scale-down` plays a big part in not downscaling "too soon", when the usage drops just for a little while. Also use `always-decrease-rw-together`, as AWS only gives you 4 provision changes per _table_.

Some of our settings in percent:

* `*-upper-threshold: 80`
* `*-lower-threshold: 40`
* `increase-*-with: 50`
* `decrease-*-with: 45`
* `num-*-checks-before-scale-down: 5`
* `always-decrease-rw-together = true`

So IMO, in response to your questions:

> Does anyone have any recommended suggestions for settings that would best compliment the limit of 4 changes per day?

Study you app's usage and use `num-*-checks-before-scale-down` and `always-decrease-rw-together` to avoid unnecessary downscaling

> Do you think the documentation should be updated to warn users about the update limit?

This is an AWS limitation that people using DynamoDB should be aware of. The dynamic-dynamodb docs do mention, in passing, stuff about "unnecessary downscale".

> Do you think there should be a notification when updates can no longer be performed due to the throughput change limit of 4 being reached? (I think it should because it can be confusing as to why the dynamic-dynamodb isn't issuing changes.)

The logs do throw an exception already:

```
[WARNING] - TableName - LimitExceededException: Subscriber limit exceeded: Provisioned throughput can be decreased 4 times within the same day. Number of Decreases Today: 4. Last decrease time: Monday, July 3, 2015 4:05:00 AM UTC. Request time: Monday, July 3, 2015 10:45:19 AM UTC
```

**Comment by radleta** [comment]
@tcanabarro Thanks so much for the detail answers. These all make sense.

You're explanation of how you do it and your recommendation is excellent. It would be nice to capture it into the docs somehow for others following behind me. Thoughts?

**Comment by sebdah** [comment]
@tcanabarro thanks for a good answer on this.

@radleta. It could probably be mentioned more clearly in the docs. But I also think that the limitations of DynamoDB is things that the user base should in general be aware of. I also try to avoid being tied to hard to those limits as they change over time as AWS are releasing new functionality and remove or loosens some of the current limitations.

If you are interested in supplying a pull request with more clear documentation I'd gladly review and merge it.

Closing this for now. Reopen if need be.

**Comment by radleta** [comment]
@tcanabarro Makes sense. Thanks. To your point, I was able to open a request with Amazon Customer Service and they were nice enough to increase our the limit. It might not work for everyone but we had ours increased to 24 per day to help smooth out the usage levels.
