### ISSUE TITLE
lookback-window-start param is forced to be no less than 5 minutes

### ISSUE THREAD

**Issue by tluolamo** [sebdah/dynamic-dynamodb#259]
From sample conf file:

#Dynamic DynamoDB fetches data from CloudWatch in a window that streches between now()-15 and now()-10 minutes.
#Please note that it might not be set to less than 5 minutes
lookback-window-start = 15

AWS now reporting metrics per minute, so perhaps you should allow this setting to be set to 1

https://aws.amazon.com/about-aws/whats-new/2015/08/dynamodb-update-enhanced-metrics-for-better-operational-insight/

Additionally I think this is appearing to cause some unexpected behaviour when combined with absolute value to increase during throttling. So say it is set as above (to 15) and I set my table to increase provisioning when there are more than 10 throttles. It seems like as long as there were more than 10 throttles within the window (in this example 15 minutes) dynamic dynamodb will increase the provisioned capacity several times, depending on how frequently it is ran. Specifically I have mine now set to run every minute since the data is provided every minute and I see several increases although after the first increase throttling stopped and provisioned capacity is clearly above the needed value. However I haven't run an isolated test, so it is possible if I misunderstood how this setting works that something else is going on on my system too.

Oh I should mention this is on the latest version from pypi:
dynamic-dynamodb==2.0.0

**Comment by aaaristo** [comment]
+1

**Comment by Sazpaimon** [comment]
One issue I've noticed with the enhanced metrics is that it doesn't seem to include provisioned throughput. It seems to still be on a delay of what appears to be 10 minutes. I've noticed during my ETL processes (where I increase the provisioned throughput of a table greatly), Dynamic DynamoDB was reporting 2500% utilization (which is impossible).  I think if Dynamic DynamoDB were to support a more recent lookback window (for example now()-5 to now() or shorter), the app will need to actually look at the DynamoDB API itself to determine the current provisioned throughput.

**Comment by Sazpaimon** [comment]
Actually, scratch that. Dynamic DynamoDB DOES look at the current provisioned throughput, not the cloudwatch metrics. The 2500% utilization was from after the ETL had completed and the throughput had been lowered, the lookback window was including the consumed throughput from during the ETL, but not taking into account the consumed throughput from that time.

**Comment by sebdah** [comment]
This has now been released in version 2.0.1

**Comment by sebdah** [comment]
Closing this since #261 was merged.
