### ISSUE TITLE
Confusing granular docs example

### ISSUE THREAD

**Issue by stephenh** [sebdah/dynamic-dynamodb#262]
On this page:

http://dynamic-dynamodb.readthedocs.org/en/latest/granular_scaling.html, there is this example:

```
If the current consumed read units is up to 0.25% no scaling will occur.
If the current consumed read units is at 0.25% or above but below 0.5% then read provisioning will be scaled up by 5%
...
```

I think instead of ".25%", ".5%", you just mean "25%", "50%", etc.

Also, for the last one:

```
If the current consumed read units is at 5% or above read provisioning will be increased by 100%
```

Does that mean if provisioned is 100 units, consumed is 500 units, that read provisioning will be bumped by 100 units? Or 500 units? I think a concrete example would help users quickly understand.

Also, what's the difference between "increase-reads-with", "increase-consumed-reads-", and "increase-throttled-by-consumed-reads-", and "increase-throttled-by-provisioned-reads-"?

If provisioned is 100 units, are consuming 80 units, and we have 10 throttle events, would increase-throttled-by-consumed apply x% to 80, and increase-throttled-by-provisioned apply x% to 100?

Why does "increase-throttled-by" have separate config options for consumed/provisioned, but increase-consumed-reads and increase-reads does not?

It seems like it would be more orthogonal if there was:
- increase-consumed-reads-with = x
- increase-consumed-reads-unit = percent/units
- increase-consumed-reads-apply-to = consumed/provisioned
- increase-consumed-reads-with-scale = { map }
- (Can only set either -with or -with-scale)
- increase-throttled-by-reads-with = x
- increase-throttled-by-reads-unit = percent/units
- increase-throttled-by-reads-apply-to = consumed/provisioned
- increase-throttled-by-reads-scale = { map }
- (Remove increase-reads)

E.g. two choices: scale on % consumed, or scale on throttled events. And for each choice, pick -with or -scale. And whether to apply -with/-scale number against the current consumed or provisioned units. 

...does that sound right, at least in an ideal world/with no backwards compatibility?

It would also be slick if -with = x and -scale = { map } could be combined into just -with = x or { map }, given they are mutually exclusive AFAIU.

Sorry for the long, rambling issue. Also understood if 100% of this is due to wanting to maintain backwards compatibility with existing flags. If so, a short intro/disclaimer to what are legacy flags/or non-ideal flags based on newer flags, would be really helpful.

We've been using dynamic dynamo for awhile very successfully, so thanks!

**Comment by sebdah** [comment]
Closing as too old. Sorry.
