### ISSUE TITLE
Slow capacity increase

### ISSUE THREAD

**Issue by henriksjostrom** [sebdah/dynamic-dynamodb#264]
I have some problems that dynamic dynamo seems to be very slow at scaling up. I have set check-interval: 300 so it should check every 5 minutes but it often takes more than 20 minutes to scale.

I'm not sure how to make it react faster or what is causing it to be so slow. Do you have any tips/suggestions on how to speed it up?

Dynamo scaling:
<img width="902" alt="screen shot 2015-09-07 at 16 33 48" src="https://cloud.githubusercontent.com/assets/2777441/9719361/d6dfb3bc-5583-11e5-8090-60fb0c86c6a6.png">

Dynamic config:

```
[global]

region: eu-west-1

check-interval: 300

[logging]
log-level: info

log-file: /var/log/dynamic-dynamodb.log

[default_options]

##########################################################################################
#
# 'TABLE' table throughput configuration
#
##########################################################################################
[table: TABLE]
enable-reads-up-scaling = true
enable-reads-down-scaling = true

reads-upper-threshold: 70
reads-lower-threshold: 30

increase-reads-with: 50
decrease-reads-with: 50

increase-reads-unit: percent
decrease-reads-unit: percent

min-provisioned-reads: 300
max-provisioned-reads: 1000

enable-writes-up-scaling = true
enable-writes-down-scaling = true

writes-upper-threshold: 70
writes-lower-threshold: 30

increase-writes-with: 50
decrease-writes-with: 50

increase-writes-unit: percent
decrease-writes-unit: percent

min-provisioned-writes: 100
max-provisioned-writes: 1000

allow-scaling-down-reads-on-0-percent: true
allow-scaling-down-writes-on-0-percent: true
```

**Comment by sebdah** [comment]
Hmm, yeah that looks a bit odd. Could you please provide a debug level log file illustrating this behaviour?

**Comment by piper-at-dawn** [comment]
Having the same issue.  Will try to get you a debug in the near term.

**Comment by connor-hailey-zocdoc** [comment]
@sebdah i am having the same issue. It took 20 mins until scale up even though I have check interval set to 60 seconds. Any progress on this?

**Comment by connor-hailey-zocdoc** [comment]
![capture png](https://cloud.githubusercontent.com/assets/19580401/16312549/4082ee94-3943-11e6-899c-a21b9fdbe07a.PNG)

**Comment by mnietz** [comment]
I have the same issue and now trying out these two options:

lookback-window-start
lookback-period

For a description see the docs:

http://dynamic-dynamodb.readthedocs.io/en/latest/configuration_options.html?highlight=lookback

I let you know if it works for me.

**Comment by ajaygarga** [comment]
Hi,

I am using Dynamic DynamoDB 2.4.1 but I am noticing slow capacity increase issue as well as mentioned in this ticket. It take 15 to 20 minutes for it to provision the new capacity.

Please recommend the correct values for the following to solve this issue.
lookback-window-start
lookback-period

**Comment by mnietz** [comment]
Works fine for me:

```
lookback-window-start: 2
lookback-period: 1
```

**Comment by ajaygarga** [comment]
Thanks. Check interval is 300 seconds right?. Does check interval 300 seconds is safe enough to avoid throttling given DynamoDB supports Bursting upto 300 seconds?

**Comment by mnietz** [comment]
nope, i use a 60 second check-interval. With this and the above settings you will have an almost immediately increase. But you have to deal with Amazon's decrease-limit in some way.

**Comment by ajaygarga** [comment]
Thanks for your quick response. Let me try it out as well.

**Comment by sebdah** [comment]
Closing this. Please re-open if you see fit.
