### ISSUE TITLE
Allow [ ] brackets in table regex

### ISSUE THREAD

**Issue by WalkerCodeRanger** [sebdah/dynamic-dynamodb#281]
I could not re-open #186.  We have a table regular expression like:

    [table: ^dev(-lms|-cms)?-[^-]+(?<=\d{4})(?<!2015)$]

This gives the error in the log:

     2015-12-08 19:36:45,097 - dynamic-dynamodb - ERROR - Invalid regular expression:
       "^dev(-lms|-cms)?-[^-"

You can see that the regular expression is being truncated at the right brace.  This looks to be that the config library is stopping at the first right bracket it encounters.

**Comment by sebdah** [comment]
So I have looked into this and the reason `]` is not currently supported is that it's defined as a termination character in Python's ConfigParser library. There has been some discussion about that in the Python community but no change will be introduced now in ConfigParser.

The good news is that there is a way to manually update the regular expression. I have done so in `develop`. I have also released an alpha version. @WalkerCodeRanger would you mind installing that and give it a try?

It's installed with `pip install dynamic-dynamodb==2.3.0a1`.

It looks good locally on my machine, but I would like to get some more eyes on it before releasing.

**Comment by WalkerCodeRanger** [comment]
Unfortunately, we have already worked around this issue and moved it into production.  At this time we have moved onto other things.  Eventually, I'm sure we will upgrade dynamic dynamodb at some point in the future, and when we do, we will likely try to test this.  However, that will probably not be for quite a while.
