### ISSUE TITLE
Override configuration if table matches multiple regex's

### ISSUE THREAD

**Issue by jonomacd** [sebdah/dynamic-dynamodb#282]
I would like to specify a general configuration for all tables but override that configuration for specific tables.  For example:

[table: ^testing-]
 -- config 1--

[table: ^testing-foo$]
-- config 2--

I want all testing tables to get config 1 but the specific testing-foo table to get config 2.  Is this currently possible? What do people think of this idea?

**Comment by wayne-luminal** [comment]
The `default_options` section should do what you want https://github.com/sebdah/dynamic-dynamodb/blob/master/docs/configuration_options.rst#default-configuration

**Comment by dshaffer** [comment]
No, default_options doesn't handle this.

You still have to _mention_ all the tables so they'll be monitored.  When a tables matches more than one regular expression, which set of settings is used?

**Comment by sebdah** [comment]
The first match is used afaik, others ignored.
