### ISSUE TITLE
GSI section not working

### ISSUE THREAD

**Issue by oli-g** [sebdah/dynamic-dynamodb#289]
Hi @sebdah Thank you very much for your wonderful work.

Here we have some problems with autoscaling of global secondary indexes. Check our configuration: 

```
[table: foo-staging]
...
...

[gsi: ^.index$ table: foo-staging]
...
...
```

We have table names like `foo-staging-accounts`, `foo-staging-events`, and so on. Some tables have global secondary indexes: all of them ends with the `-index` suffix.

Using the configuration file above, Dynamic DynamoDB is able to autoscale all tables correctly, but our indexes are not handled at all. For example, we have a table `foo-staging-accounts` with two global secondary indexes, named `uuid-index` and `fbid-index`: from the Dynamic DynamoDB log, we can see that `foo-staging-accounts` is autoscaled, while its two indexes are not.

What's wrong with our configuration?

**Comment by wayne-luminal** [comment]
I haven't messed with GSIs yet, but the regex for the gsi is incorrect. `.` will match one character only. Change it to `.*index` or `.*?index` to look at the whole name.
