### ISSUE TITLE
Circuit breaker return code

### ISSUE THREAD

**Issue by zar1** [sebdah/dynamic-dynamodb#292]
In order to determine whether or not the circuit breaker is open, dynamic-dynamodb checks whether or not the circuit-breaker-url returns status code 200. For my service, a healthy endpoint returns 204, rather than 200. So, according to HTTP standards, the request is a success, but according to dynamic-dynamodb the service is offline. I believe it would make more sense if any 2xx status code signified success.

**Comment by sebdah** [comment]
Released in 2.3.0

**Comment by mbravorus** [comment]
this commit destroys circuit breaker functionality completely due to an error in line 73 in circuit_breaker.py, condition should be >= 200, not > 200

should I open a new issue for this?

**Comment by sebdah** [comment]
@mbravorus Embarrassing! Thanks for reporting this. I'm shipping version 2.3.1 right now, where this is fixed.
