### ISSUE TITLE
Wrong Consumed read units

### ISSUE THREAD

**Issue by IBazylchuk** [sebdah/dynamic-dynamodb#299]
On amazon site i see that read more then capacity in some times, throttle some thouthands.

But in dynamic dynamodb log Consumed read units: 30-35%, Read throttle count: 0

And i get errors from amazon

**Comment by ckrajk** [comment]
The default value for "loopback-window-start" property is 15 minutes. If you have not changed this, dynamic dynamodb is reading 15 minute old data. If you want it to read more recent data, reduce this value and possibly "loopback-period".
