### ISSUE TITLE
can we enhance "xxx-threshold" to accept decimal instead of integer only?

### ISSUE THREAD

**Issue by duanhv** [sebdah/dynamic-dynamodb#308]
Dear!
   I'm sure many people have this problem
   because when we use dynamodb we will use many partitions (in my case, it's ~ 20 partitions ~ 200GB data)
   so if we want to configure "-down-threshold" < 30% for each partition, we have to set it is 1.5%

**Comment by sebdah** [comment]
Closing as too old. Sorry.
