### ISSUE TITLE
Support: dynamic-dynamodb can run on multi instances for HA

### ISSUE THREAD

**Issue by Tinet-AaronAn** [sebdah/dynamic-dynamodb#309]
is dynamic-dynamodb can run on multi instances for HA?

**Comment by sebdah** [comment]
Not without your involvement. There is no way for the dynamic-dynamodb instances to know of each other. I would suggest using 1 machine with an auto scaling group of min 1, max 1. That way you'd always have a running instance. Check out the Dynamic DynamoDB CloudFormation templates for examples.
