### ISSUE TITLE
Help Finessing my Scaling Config Options..

### ISSUE THREAD

**Issue by ninjada** [sebdah/dynamic-dynamodb#311]
Have a pretty continuous dynamo db pattern, a spike hits every 3-4 hours so I just want something fairly rigid to deal with it but I just can't finesse the scaling options exactly.

My current config is to set a minimum of around 600 and as soon as 145% of that is hit, up it goes to 3000 or so.

I'm running following options:

```
# How often should Dynamic DynamoDB monitor changes (in seconds)
check-interval: 60
enable-reads-autoscaling = true
# Thresholds for scaling up or down the provisioning (%)
reads-upper-threshold: 145
reads-lower-threshold: 40
# Units to increase or decrease reads with, must be either percent or units
increase-reads-unit: units
decrease-reads-unit: percent
# How many percent should Dynamic DynamoDB increase/decrease provisioning with (%)
increase-reads-with: 2000
decrease-reads-with: 80
# Maximum and minimum read provisioning
# Dynamic DynamoDB will not provision any more or less reads than this
min-provisioned-reads: 600
max-provisioned-reads: 3000
# Read Checks
num-read-checks-before-scale-down: 5
```

Unfortunately, there seems to be a 10-12minute delay before dynamo scales up as you'll see below. This is resulting in errors in my application using the table as the spike for my external data hits, but the table can't cope at the low capacity and it disconnects and waits to  reconnect. Hence the initial spike>drop>spike pattern going on here:

My dynamo usage:
[http://ninjada.com/dynamo.png](http://ninjada.com/dynamo.png)

I'm not sure why there is this delay to be honest? The initial spike easily hits > 870 (or 145% of 600), but it waits at least 10-12 checks before scaling. Where am I going wrong on this one?

**Comment by sebdah** [comment]
Closing as too old. Sorry.
