### ISSUE TITLE
Possible bug in GSI configuration parsing

### ISSUE THREAD

**Issue by dabest1** [sebdah/dynamic-dynamodb#313]
Let's say I have the following sections in Dynamic-DynamoDB configuration file. (::: represents skipped lines.)

[table: ^mytable$]
:::
[gsi: ^myindex$ table: ^mytable$]
min-provisioned-writes: 100
:::
[gsi: ^.*$ table: ^mytable$]
min-provisioned-writes: 10
:::

For some strange reason Dynamic-DynamoDB will reduce write capacity and then increase write capacity on myindex four times during roughly the first 2.5 hours of the day. I am suspecting that somehow the configuration is sometimes taken from the wildcard section, and most of the time from the specific section.

For now I can use a work around and remove the wild card section for GSI.

**Comment by sebdah** [comment]
Closing as too old. Sorry.
