### ISSUE TITLE
CPU usage on cloud parser instances has increased

### ISSUE THREAD

**Issue by jwvhoek** [sebdah/dynamic-dynamodb#320]
The CPU usage on both cloud parser 1 and 2 has increased a lot over the last few days, peaking at 100% a lot.

`CLOUD PARSER 1`
![cloud-parser-1-2017-01-18-08-53-04](https://cloud.githubusercontent.com/assets/516371/22055626/5e0fbd30-dd5c-11e6-8ce4-a229cb24b288.png)

`CLOUD PARSER 2`
![cloud-parser-2-2017-01-18-08-56-40](https://cloud.githubusercontent.com/assets/516371/22055627/5e17c6a6-dd5c-11e6-83da-9192c52b7ae0.png)

**Comment by sebdah** [comment]
Need more details about the running process, system details etc to be able to do anything here. Closing.
