### ISSUE TITLE
Pin requirements.txt to specific versions

### ISSUE THREAD

**Issue by erikcw** [sebdah/dynamic-dynamodb#324]
The package is now failing to install from pip because logutils broke their pip install in 0.3.4.

Pinning the dependencies in requirements.txt to specific versions (`==` instead of `>=`) will prevent this from happening in the future.

https://bitbucket.org/vinay.sajip/logutils/issues/2/logutils-install-with-pip-fails

**Comment by sebdah** [comment]
Thanks! A fix for this has been released.
