### ISSUE TITLE
Doesn't scale down less than 3 writes 

### ISSUE THREAD

**Issue by orest-p** [sebdah/dynamic-dynamodb#326]
Hello
I spotted that the minimum I can scale down on writes is 3, and then downscaling stops
Is this something configurable? I have many idle tables in dev and qa environments and need to scale down to 1 write.
I have following options enabled  
allow-scaling-down-writes-on-0-percent: true
min-provisioned-writes: 1

Thanks!

**Comment by sebdah** [comment]
This seems very strange. I'm not able to reproduce. Please post your full configuration file along with any command line arguments you might be using please.
