### ISSUE TITLE
When adding the table name 

### ISSUE THREAD

**Issue by jeromemyers** [sebdah/dynamic-dynamodb#327]
When call the service with the following parameters 
`sudo dynamic-dynamodb -c /opt/monitoring/dynamic-dynamodb.conf -r {} --aws-access-key-id {} --aws-secret-access-key {} --table {} --run-once`

I get `min_provisioned_reads may not be lower than 1 for table avista-notifi-dev` but if I remove the table portion it runs fine.

**Comment by sebdah** [comment]
Not sure I understand what you're trying to accomplish here? Could you also dump your `dynamic-dynamodb.conf` file for issue completeness?
