### ISSUE TITLE
Cannot recognize the same GSI name in different tables

### ISSUE THREAD

**Issue by cjy0125** [sebdah/dynamic-dynamodb#330]
While using the same GSI name in 2 different tables, dynamicdynamodb will treat them as the same GSI.
Following is the log for reproduce this issue.
[dynamic-dynamodb2.txt](https://github.com/sebdah/dynamic-dynamodb/files/1010701/dynamic-dynamodb2.txt)
There are two tables: "scan-result", "scan-result"
And both of these 2 tables have a GSI named "by_gid"

It should recognize bind GSI name with table name as an identified key.

**Comment by sebdah** [comment]
A fix for this has been released in the latest version of dynamic-dynamodb.
