### ISSUE TITLE
Failed to install pip on m3.medium

### ISSUE THREAD

**Issue by meirf** [sebdah/dynamic-dynamodb#335]
I'm following http://dynamic-dynamodb.readthedocs.io/en/latest/cloudformation_template.html **precisely**. I'm using instance type `m3.medium`.

Cloud formation shows:

> CREATE_FAILED | AWS::CloudFormation::WaitCondition | WaitCondition | WaitCondition received failed message: 'Failed to install pip' for uniqueId: i-#############'

I can't see more than this right now because the instance gets terminated when this fails.

**Comment by sebdah** [comment]
Thanks for the report. Would be great if you could try to log in as quickly as possible and get the details from the log. Or alternatively see if you can modify the output to be sent in an email / stored on s3 / or increase the timeout or so.
