### ISSUE TITLE
can not run the CloudFormation stack, encounter 2 exceptions

### ISSUE THREAD

**Issue by flightjim** [sebdah/dynamic-dynamodb#338]
hi,
i need to launch a new dynamic-dynamodb instance, so i use CloudFormation at https://dynamic-dynamodb.readthedocs.io/en/latest/cloudformation_template.html# to run a CloudFormation stack.
several months ago i can run successfully several time. thanks this tool!

but today, i run this stack many time, all fails.
if i take default parameters like take EC2 instance type as "t2.micro", CloudFormation will fail and report me as: 
Virtualization type 'hvm' is required for instances of type 't2.micro'. Ensure that you are using an AMI with virtualization type 'hvm'. For more information, see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html. Launching EC2 instance failed.

i google some urls and decide to use another EC2 instance type as "m3.medium", then above exception pass, but new exception occur:
WaitCondition received failed message: 'Failed to install dynamic-dynamodb package from pip repository' for uniqueId: i-xxxxxxxxxx

could you check this issue? this is a powerful tool, and we reply on it.
thanks!

**Comment by sebdah** [comment]
@flightjim Thanks for reporting this. I have updated the AMI references in the PR above. Do you think you could try with that CloudFormation template instead?

**Comment by flightjim** [comment]
hi,
this fix really work!
the key change is the AMI type id. i am in us-west-2 region, after i change my CloudFormation dynamic-dynamodb.json, with the latest us-west-2 AMI id, i can run successfully. the 2 issues i reported are all gone.
